services:
    pgdatabase:
        image: postgres:14
        env_file:
            - .env
        volumes:
            - "./transactions_postgres_data:/var/lib/postgresql/data:rw"
        ports:
            - "5432:5432"
        networks:
            - cdc_batch

    pgadmin:
        image: dpage/pgadmin4
        env_file:
            - .env
        ports:
            - "5050:80"
        depends_on:
            - pgdatabase
        networks:
            - cdc_batch

networks:
    cdc_batch:
        external: true